language: php

php:
  - 5.5

before_install:
  - php --info
  - sudo pwd
  - whoami
  - groups travis
  - cat /etc/passwd
  - sudo apt-get update -y

install:

# Install latest version of Puppet
# Default version 2.7 does not allow to use modules

#  - sudo apt-get install -y --force-yes puppet
#  - sudo puppet --version


  - sudo wget https://apt.puppetlabs.com/puppetlabs-release-precise.deb
  - sudo dpkg -i puppetlabs-release-precise.deb
  - sudo apt-get update -y
  - sudo apt-get install puppet -y

  - sudo puppet --version


  - sudo puppet module install puppetlabs-stdlib
  - sudo puppet module install gajdaw-php5
  - sudo puppet module install puppetlabs-mysql
  - sudo puppet apply puppet/manifest.pp

  - sudo mkdir -p /var/www
  - sudo ln -s  "$(pwd)/web" /var/www/html


  - sudo /etc/init.d/apache2 restart

before_script:

  - composer self-update


  - mkdir -p /tmp/symfony2app/app/cache
  - mkdir -p /tmp/symfony2app/app/logs
  - mkdir -p /tmp/symfony2app/vendor/

  - ls -la /tmp
  - ls -la /tmp/symfony2app
  - ls -la /tmp/symfony2app/app
  - ls -la /tmp/symfony2app/app/cache
  - ls -la /tmp/symfony2app/app/logs
  - ls -la /tmp/symfony2app/vendor


  - composer install --no-interaction
  - pwd
  - ls -la


  - sudo chmod -R 777 /tmp/symfony2app/app/cache /tmp/symfony2app/app/logs
  - app/console cache:warmup --env=dev
  - app/console cache:warmup --env=prod
  - sudo chmod -R 777 /tmp/symfony2app/app/cache /tmp/symfony2app/app/logs

  - ls -la /tmp/symfony2app/app/cache
  - ls -la /tmp/symfony2app/app/logs



#  - ls -la app
#  - ls -la app/logs
#  - ls -la app/cache
#  - sudo chmod -R 777 app/cache app/logs
#  - app/console cache:warmup --env=dev
#  - sudo chmod -R 777 app/cache app/logs
#  - ls -la app
#  - ls -la app/logs
#  - ls -la app/cache


#  - chmod o+w app/logs
#  - ls -la app
  - chmod o+w /tmp/symfony2app/app/logs
  - ls -la /tmp/symfony2app/app

  - mysql -u root < 00-extra/db/create-empty-database.sql
  - app/console doctrine:schema:update --force


#  - sudo chmod -R 777 app/cache app/logs
#  - ls -la app
#  - ls -la app/logs
#  - ls -la app/cache


  - sudo chmod -R 777 /tmp/symfony2app/app/cache /tmp/symfony2app/app/logs
  - ls -la /tmp/symfony2app/app/cache
  - ls -la /tmp/symfony2app/app/logs


#change ownership
#  - chown -R travis:travis app/logs
#  - ls -la app
#  - ls -la app/logs
  - chown -R travis:travis /tmp/symfony2app/app/logs
  - ls -la /tmp/symfony2app/app
  - ls -la /tmp/symfony2app/app/logs

#change the rights right before you run application
#  - chmod -R 777 app/cache app/logs
#  - ls -la app
#  - ls -la app/logs
  - sudo chmod -R 777 /tmp/symfony2app/app/cache /tmp/symfony2app/app/logs
  - ls -la /tmp/symfony2app/app/cache
  - ls -la /tmp/symfony2app/app/logs


#change the rights right before you run application
#  - chmod -R 777 app/logs/dev.log
#  - ls -la app
#  - ls -la app/logs

#change the rights right before you run application
#  - sudo chmod -R 777 app/logs/dev.log
#  - ls -la app
#  - ls -la app/logs


#Sessions go to /tmp/sessions
  - sudo mkdir -p /tmp/sessions
  - sudo chmod -R 777 /tmp/sessions
  - ls -la /tmp/sessions
  - ls -la /tmp

  - sleep 5

after_failure:

  #Print app's log
  - ls -la /tmp/symfony2app/app/logs
  - ls -la /tmp/symfony2app/app/logs/prod
#  - cat /tmp/symfony2app/app/logs/dev.log
  - cat /tmp/symfony2app/app/logs/prod/prod.log

  #Print Apache's log
  - ls -la /var/
  - ls -la /var/log/
  - ls -la /var/log/apache2/




script:
  - bin/behat --verbose features/home.feature
  - bin/behat --verbose features/rivers.feature

  - bin/behat --verbose --stop-on-failure

notifications:
  email: false
